bot:
  token: 6831194245:AAGlG3zTUD_Lsm4lAB5aw0QXkEiFt9IT__0
  name: myrandom123_bot

spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
    dead_letter_topic: notification-retry


  datasource:
    url: jdbc:postgresql://localhost:5432/demo_telegram_bot
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/auth/realms/Fintrack
          jwk-set-uri: http://localhost:8443/auth/realms/Fintrack/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

keycloak:
  realm: Fintrack
  resource: fintrack-app
  #  auth-server-url: https://demo.docengine.tech/auth/ #docker container
  auth-server-url: http://localhost:8443/auth/ #docker container
  credentials:
    username: 'admin'
    password: 'admin'
    client-id: 'fintrack-app' # admin account for creating users
    secret: 'qOmECg1MXkL4ip2lwISCV0NEqokWpEJ6'
    provider: secret

  grant-type: password
  tokenUrl: http://localhost:8443/auth/realms/Fintrack/protocol/openid-connect/token