server.port: 8082
bot:
  token: 6866869281:AAHkeris_QJgrkfmR7HV67hw168sLPYhzYw
  name: fintrack_notification_bot

fontEnd:
  Url: http://localhost:4200

spring:
  application:
    name: telegram-service

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
    dead_letter_topic: notification-retry


  datasource:
    url: jdbc:postgresql://34.142.208.161:2345/fintrack_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak-fintrack.sythorng.site/auth/realms/Fintrack
          jwk-set-uri: https://keycloak-fintrack.sythorng.site/auth/realms/Fintrack/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

keycloak:
  realm: USER_SERVICE
  resource: client-app
  #  auth-server-url: https://demo.docengine.tech/auth/ #docker container
  auth-server-url: https://keycloak-fintrack.sythorng.site/auth/ #docker container
  credentials:
    username: 'admin'
    password: 'admin'
    client-id: 'fintrack-app' # admin account for creating users
    secret: 'MYhYGrLOk1UNwK9eTaULwIye39hVujPi'
    provider: secret

  grant-type: password
  tokenUrl: https://keycloak-fintrack.sythorng.site/auth/realms/Fintrack/protocol/openid-connect/token