spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TestN
    username: postgres
    password: runrun2001

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://fintrack-keycloak.kbaenak.tech/auth/realms/Fintrack
          jwk-set-uri: https://fintrack-keycloak.kbaenak.tech/auth/realms/Fintrack/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8089

Base:
  url: http://localhost:8081/api/v1/

