spring:
  datasource:
    url: jdbc:postgresql://localhost:33007/mini_project_db
    username: my_user
    password: my_password

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak-fintrack.sythorng.site/auth/realms/Fintrack
          jwk-set-uri: https://keycloak-fintrack.sythorng.site/auth/realms/Fintrack/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8089

Base:
  url: http://localhost:8081/api/v1/

