spring:
  datasource:
    url: jdbc:postgresql://34.142.208.161:2345/fintrack_db
    username: postgres
    password: 1234

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak-fintrack.sythorng.site/auth/realms/Fintrack
          jwk-set-uri: https://keycloak-fintrack.sythorng.site/auth/realms/Fintrack/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8089

Base:
  url: http://localhost:8081/api/v1/

