version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:arm64
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:arm64
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"




# Add more services or configurations as needed
