server:
  port: 8081
spring:
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/auth/realms/SpringMiniProject
          jwk-set-uri: http://localhost:8443/auth/realms/SpringMiniProject/protocol/openid-connect/certs
keycloak:
  realm: SpringMiniProject
  resource: mini-project-app
  #  auth-server-url: https://demo.docengine.tech/auth/ #docker container
  auth-server-url: http://localhost:8443/auth/ #docker container
  credentials:
    username: 'admin'
    password: 'admin'
    client-id: 'mini-project-app' # admin account for creating users
    secret: '71WdvU3R9FuBxuh8wnIkaAQHfGieGla0'
    provider: secret

  grant-type: password
  tokenUrl: http://localhost:8443/auth/realms/SpringMiniProject/protocol/openid-connect/token

spring.mail:
  host: smtp.gmail.com
  port: 587
  username: soccerdatehrd@gmail.com
  password: nolwmacooizbnviz