spring:
#  datasource:
#    #    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/task
#    username: postgres
#    password: admin
#  #    username: postgres
#  #    password: runrun2001
#  #    url: jdbc:postgresql://localhost:5432/kdmv
  datasource:
    url: jdbc:postgresql://localhost:5432/task
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://fintrack-keycloak.kbaenak.tech/auth/realms/Fintrack
          jwk-set-uri: https://fintrack-keycloak.kbaenak.tech/auth/realms/Fintrack/protocol/openid-connect/certs

server:
  port: 8088

Base:
  url: http://localhost:8089/api/v1/